EGG-Haunolding_Management-System/EGG-Haunolding_Management-System/Controllers/TopicController.cs
using EGG_Haunolding_Management_System.Class;
using EGG_Haunolding_Management_System.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EGG_Haunolding_Management_System.Controllers
{
    public class TopicController : Controller
    {
        private ITopicStore TopicStore { get; }
        private IConfiguration Config { get; }
        public TopicController(ITopicStore topicStore, IConfiguration config)
        {
            TopicStore = topicStore;
            Config = config;
        }

        public IActionResult Index()
        {
            List<TopicItem> topics = TopicStore.GetAllTopics();
            string topic = Config.GetValue<string>("TopicName");

            return View(new TopicViewModel { Topics = topics, TopicName = topic });
        }

        public IActionResult Delete(int id)
        {
            TopicStore.DeleteTopic(id);

            return RedirectToAction("Index");
        }

        public IActionResult NewTopic()
        {
            string topic = Config.GetValue<string>("TopicName");
            return View("NewTopic", new NewTopicViewModel { Topic = topic });
        }

        public IActionResult AddTopic(NewTopicViewModel model)
        {
            if(!ModelState.IsValid)
                return View("NewTopic", model);

            string prefix = Config.GetValue<string>("TopicName");

            if(model.Topic.Length < prefix.Length || prefix != model.Topic.Substring(0, prefix.Length))
            {
                ModelState.AddModelError(string.Empty, $"Das Topic muss mit '{prefix}' beginnen.");
                return View("NewTopic", model);
            }

            string topic = model.Topic.Substring(prefix.Length);

            if(String.IsNullOrEmpty(topic))
            {
                ModelState.AddModelError(string.Empty, "Gib ein Topic ein!");
                return View("NewTopic", model);
            }

            if(TopicStore.CheckIfTopicExists(topic))
            {
                ModelState.AddModelError(string.Empty, "Dieses Topic existiert bereits!");
                return View("NewTopic", model);
            }
            
            TopicStore.AddTopic(new TopicItem(0, topic));

            return RedirectToAction("Index");
        }
    }
}

EGG-Haunolding_Management-System/EGG-Haunolding_Management-System/Controllers/UserController.cs
using EGG_Haunolding_Management_System.Class;
using EGG_Haunolding_Management_System.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EGG_Haunolding_Management_System.Controllers
{
    public class UserController : Controller
    {
        private IUserStore UserStore { get; }
        public UserController(IUserStore userStore)
        {
            UserStore = userStore;
        }

        public IActionResult Index()
        {
            List<UserItem> users = UserStore.GetUsers();

            return View(new UserViewModel { Users = users });
        }

        public IActionResult Delete(string username, UserViewModel model)
        {
            UserStore.DeleteUser(username);

            return RedirectToAction("Index");
        }

        public IActionResult Edit(string username)
        {
            return RedirectToAction("Index", "Edit", new { userId = username });
        }
    }
}

EGG-Haunolding_Management-System/EGG-Haunolding_Management-System/Views/Shared/_Layout.cshtml
@using EGG_Haunolding_Management_System.Class
@inject AuthenticationLogic authentication

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EGG_Haunolding_Management_System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EGG_Haunolding_Management_System.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-wind text-success"></i> Energiegemeinschaft Haunolding
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.User.Identity.IsAuthenticated)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Übersicht</a>
                        </li>
                        }
                        @if (authentication.TryGetRoleOfUser(Context) is string role && role == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Benutzer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Topic" asp-action="Index">Topics</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if(authentication.TryGetLoggedInUser(Context) is string username)
                        {
                            <li class="nav-item">
                                <div class="navbar-text text-dark">Eingeloggt als @username |</div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>